### ISSUE TITLE
Minimum supported library

### ISSUE THREAD

**Issue by binaykumarrana** [JarvanMo/ExoPlayerVideoView#10]
The minimum supported library is 17 can I override this and use for 14API?

**Comment by JarvanMo** [comment]
Suggest not to do this.This library is based on `ExoPlayer` , and here's peek from [Exo developer guide](https://google.github.io/ExoPlayer/guide.html)：\
```
ExoPlayer’s standard audio and video components rely on Android’s MediaCodec API, which was 
released in Android 4.1 (API level 16). Hence they do not work on earlier versions of Android. Widevine
common encryption is available on Android 4.4 (API level 19) and higher
```
However the minimum support in Exo project is 14.But I never test that.You can have a try because there's not too many higher apis in this project.
